name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.2']

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler: 2.3
        bundler-cache: true
      env:
        BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}:x-oauth-basic
    - name: Run tests
      run: bundle exec rake
